import React from 'react';
import Navbar from '../../Components/navbar';
import 'katex/dist/katex.min.css';

const CNNInfo = () => {
    return (
        <>
            <Navbar currentPage="Convolutional Neural Networks" visualizer="cnn" />
            <div className="info-container-2">
                <div className="info-section">
                    <h2>Convolutional Neural Networks (CNN)</h2>
                    <p>
                        Convolutional Neural Networks (CNNs) are a type of artificial neural network designed for
                        processing structured grid-like data, such as images. They are particularly effective in image
                        recognition and computer vision tasks due to their ability to automatically learn spatial
                        hierarchies of features.
                    </p>

                    <h3>Structure of a Convolutional Neural Network</h3>
                    <p>
                        CNNs typically consist of the following layers:
                    </p>
                    <ol>
                        <li><strong>Convolutional Layers:</strong> These layers apply convolution operations to the
                            input data, extracting features through filters or kernels.</li>
                        <li><strong>Pooling Layers:</strong> Pooling layers downsample the feature maps generated by
                            the convolutional layers, reducing the spatial dimensions of the data.</li>
                        <li><strong>Fully Connected Layers:</strong> These layers process the extracted features and
                            make predictions based on them. They are similar to the dense layers in traditional neural networks.</li>
                    </ol>

                    <h3>Convolution Operation</h3>
                    <p>
                        The convolution operation involves sliding a filter (kernel) over the input data and computing
                        the dot product between the filter and the input at each position. This process generates a
                        feature map that highlights different aspects of the input.
                    </p>
                    <p>
                        The output of the convolution operation is determined by the filter size, stride, and padding
                        applied during the operation.
                    </p>

                    <h3>Pooling Operation</h3>
                    <p>
                        Pooling layers reduce the spatial dimensions of the input data by applying operations such as
                        max pooling or average pooling. These operations help in reducing the computational complexity
                        of the network and making it more robust to variations in input.
                    </p>

                    <h3>Applications</h3>
                    <p>
                        CNNs have revolutionized various fields, including:
                    </p>
                    <ul>
                        <li><strong>Image Recognition:</strong> Classifying objects in images.</li>
                        <li><strong>Object Detection:</strong> Detecting and localizing objects within images.</li>
                        <li><strong>Facial Recognition:</strong> Identifying and verifying individuals based on facial features.</li>
                        <li><strong>Medical Image Analysis:</strong> Analyzing medical images for diagnosis and treatment planning.</li>
                    </ul>
                    <button title='Learn more'>
                        <a href="https://en.wikipedia.org/wiki/Convolutional_neural_network" target="_blank" rel="noopener noreferrer">Learn more</a>
                    </button>
                </div>
            </div>
        </>
    );
};

export default CNNInfo;
